import { getDatabase } from '@netlify/database';
import { getUser } from '@netlify/identity';
import { CONFIG } from '../../variant-config.js';

export function json(body,status=200){return Response.json(body,{status,headers:{'cache-control':'no-store'}})}
export async function currentUser(){return await getUser()}
export function db(){return getDatabase()}
export function rowToDomain(row){if(!row)return null;const c=row.canonical_state&&typeof row.canonical_state==='object'?row.canonical_state:{};return{id:row.id,category:row.category,title:row.title,counterpartyLabel:row.counterparty_label||'',amountMinor:row.amount_minor==null?null:Number(row.amount_minor),currency:row.currency||'',stage:row.stage||'UNKNOWN',state:row.state,nextActor:row.next_actor,attentionDate:row.attention_date?String(row.attention_date).slice(0,10):null,nextActionText:row.next_action_text||'',summary:row.state_summary||'',evidence:Array.isArray(row.evidence)?row.evidence:[],history:Array.isArray(row.history)?row.history:[],version:row.version,createdAt:row.created_at,updatedAt:row.updated_at,resolvedAt:row.resolved_at,deletedAt:row.deleted_at,corrections:Array.isArray(row.corrections)?row.corrections:[],lastDelta:row.last_delta||null,canonicalState:c,facts:c.facts||[],actors:c.actors||[],events:c.events||[],commitments:c.commitments||[],decisions:c.decisions||[],uncertainties:c.uncertainties||[],contradictions:c.contradictions||[],missingConfirmations:c.missingConfirmations||[],dependencies:c.dependencies||[],provenance:c.provenance||[],resolutionCriteria:c.resolutionCriteria||[]}}
export async function ownedItem(userId,id){const d=db();const rows=await d.sql`SELECT * FROM ulomis_threads WHERE id=${id}::uuid AND user_id=${userId} AND variant=${CONFIG.code} AND deleted_at IS NULL LIMIT 1`;return rows[0]||null}
export async function logEvent({userId=null,sessionId=null,name,category=null,milestone=null,referralId=null,meta={}}){const d=db();await d.sql`INSERT INTO ulomis_events(user_id,session_id,variant,name,category,milestone,referral_id,meta) VALUES(${userId},${sessionId},${CONFIG.code},${name},${category},${milestone},${referralId},${JSON.stringify(meta)}::jsonb)`}
export async function recentAiCount(userId,sessionId){const d=db();if(userId){const r=await d.sql`SELECT count(*)::int AS n FROM ulomis_events WHERE user_id=${userId} AND variant=${CONFIG.code} AND name='ai_reconstruct' AND created_at>now()-interval '1 hour'`;return r[0]?.n||0}if(sessionId){const r=await d.sql`SELECT count(*)::int AS n FROM ulomis_events WHERE session_id=${sessionId} AND variant=${CONFIG.code} AND name='ai_reconstruct' AND created_at>now()-interval '1 hour'`;return r[0]?.n||0}return 0}
